### ISSUE TITLE
[Other issue]: Turttlebot3 is not registering

### ISSUE THREAD

**Issue by harshp1509** [open-rmf/fleet_adapter_template#31]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I want to add custom task in my project but when i am running fleet adapter using this below adapter file than it is registering in rmf side:-

```
<?xml version='1.0' ?>

<launch>

  <arg name="fleet_name" default="turtlebot3" description="Name of this fleet of turtlebot3 robots"/><!--fleet_nameをturtlebot3に修正-->
  <arg name="use_sim_time" default="true" description="Use the /clock topic for time to sync with simulation"/><!--use_sim_timeをtrueに修正-->
  <arg name="nav_graph_file" description="Nav graph required by fleet adapter"/>

  <group>
    <include file="$(find-pkg-share rmf_fleet_adapter)/fleet_adapter.launch.xml">

      <!-- The name and control type of the fleet -->
      <arg name="fleet_name" value="$(var fleet_name)"/>
      <arg name="control_type" value="full_control"/>

      <!-- The graph that this fleet should use for navigation -->
      <arg name="nav_graph_file" value="$(var nav_graph_file)" />

      <!-- The nominal linear and angular velocity of this fleet's vehicles -->
      <arg name="linear_velocity" value="0.15"/>
      <arg name="angular_velocity" value="0.75"/>

      <!-- The nominal linear and angular acceleration of this fleet's vehicles -->
      <arg name="linear_acceleration" value="0.1"/>
      <arg name="angular_acceleration" value="0.1"/>

      <!-- The radius of the circular footprint of this fleet's vehicles -->
      <arg name="footprint_radius" value="0.105"/>
      <!-- Other robots are not allowed within this radius --> 
      <arg name="vicinity_radius" value="0.15"/>

      <!-- Whether to use sim time -->
      <arg name="use_sim_time" value="$(var use_sim_time)"/>

      <!-- How long it can be delayed before we give up and start over -->
      <arg name="delay_threshold" value="15.0"/>

      <!-- Don't make the tinyRobot wait long to retry -->
      <arg name="retry_wait" value="10.0"/>

      <!-- Give everything time to discover -->
      <arg name="discovery_timeout" value="60.0"/>

      <!-- Can the robot drive backwards -->
      <arg name="reversible" value="true"/>

      <!-- Whether it can perform deliveries -->
      <arg name="perform_deliveries" value="false"/>
      <!-- Whether it can perform loop -->
      <arg name="perform_loop" value="true"/>
      <!-- Whether it can perform cleaning -->
      <arg name="perform_cleaning" value="false"/>
      <!-- What the robot should do once it finishes its tasks -->
      <arg name="finishing_request" value="nothing"/>

      <!-- TODO Update these values with actual specs -->
      <!-- Battery parameters -->
      <arg name="battery_voltage" value="11.1"/>
      <arg name="battery_capacity" value="19.98"/>
      <arg name="battery_charging_current" value="1.0"/>

      <!-- Physical parameters -->
      <arg name="mass" value="1.0"/>
      <arg name="inertia" value="0.0055"/>
      <arg name="friction_coefficient" value="0.22"/>
      
      <!-- Power systems -->
      <arg name="ambient_power_drain" value="20.0"/>
      <arg name="tool_power_drain" value="0.0"/>
      
      <!-- Whether to consider battery drain for task planning -->
      <arg name="drain_battery" value="false"/>

      <!-- Battery level at which the robot ceases to operate -->
      <arg name="recharge_threshold" value="0.1"/>
      
    </include>
  </group>
</launch>
```

but when i am trying using config file it is not  registering and below is my turtlebot3 config file . so what can be the issue with this ?

```
# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "turtlebot3"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "park" # [park, charge, nothing]

# TinyRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for tinyRobot1
  ros2_tb3_0:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "turtlebot_world"
        waypoint: "tb3_0_start"
        orientation: 0.0 # radians
      charger:
        waypoint: "tb3_0_start"
```
