### ISSUE TITLE
[Other issue]: Facing location compute error: Unable to compute a location on the navigation graph for robot being added to fleet

### ISSUE THREAD

**Issue by Anisha-thakkar6** [open-rmf/fleet_adapter_template#32]
### Before proceeding, is there an existing issue or discussion for this?

- [x] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I am trying to integrate my robot to rmf through fleet_adapter. I have already successfully ran the free fleet example so all the features are running successfully. I am using Ubuntu'22, ROS2 humble, RMF- Jazzy (src build)

I am running cartographer example in the robot and trying to connect to the server where rmf is running, communication is established (zenoh bridge is working fine). But while trying to run the fleet adapter it through following logs showing unable to compute the robot location added to fleet.I have given intial pose, I have given reference co-ordinates  accordingly. I am not sure what is missing.

Fleet adapter logs:
```
ros2 launch free_fleet_examples nav2_tb3_simulation_fleet_adapter.launch.xml  server_uri:="ws://localhost:8000/_internal"
[INFO] [launch]: All log files can be found below /home/einfochips/.ros/log/2025-02-03-15-53-44-496320-AHMCPU2642-193866
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [fleet_adapter.py-1]: process started with pid [193885]
[fleet_adapter.py-1] [retreat_to_charger_interval] value is not provided, default to 10 seconds
[fleet_adapter.py-1] Finishing request: charge
[fleet_adapter.py-1] Fleet is configured to perform ChargeBattery as finishing request
[fleet_adapter.py-1] Maximum delay is not provided, default to 10.0
[fleet_adapter.py-1] [INFO] [1738578225.197141321] [smartrover_fleet_adapter]: Parameter [discovery_timeout] set to: 60.000000
[fleet_adapter.py-1] [INFO] [1738578225.201142592] [smartrover_fleet_adapter]: Registering to query topic rmf_traffic/query_update_1
[fleet_adapter.py-1] [INFO] [1738578225.212191446] [smartrover_fleet_adapter]: Mirror handling new sync of 1 queries from schedule node [5cc3a7c7-83ca-4230-adfb-c49355d0af8c]
[fleet_adapter.py-1] [INFO] [1738578226.268149025] [smartrover_command_handle]: Transformation error estimate for L1: 6.6409171819835375
[fleet_adapter.py-1] [INFO] [1738578226.272899841] [smartrover_fleet_adapter]: Attempting to connect to ws://localhost:8000/_internal
[fleet_adapter.py-1] [INFO] [1738578226.273271272] [smartrover_fleet_adapter]: Fleet [smartrover] is configured to perform delivery tasks
[fleet_adapter.py-1] [INFO] [1738578226.273302781] [smartrover_fleet_adapter]: Fleet [smartrover] is configured to perform patrol tasks
[fleet_adapter.py-1] [INFO] [1738578226.273338949] [smartrover_fleet_adapter]: Finished configuring Easy Full Control adapter for fleet [smartrover]
[fleet_adapter.py-1] [INFO] [1738578226.274791319] [smartrover_fleet_adapter]: Succesfully connected to ws://localhost:8000/_internal
[fleet_adapter.py-1] [INFO] [1738578226.274871714] [smartrover_fleet_adapter]: Connected to server
[fleet_adapter.py-1] [INFO] [1738578226.274897328] [smartrover_fleet_adapter]: Sent all updates
[fleet_adapter.py-1] [INFO] [1738578226.274916382] [smartrover_fleet_adapter]: Attempting queue flush if connected
[fleet_adapter.py-1] [INFO] [1738578226.278569358] [smartrover_command_handle]: Unable to get transform between base_footprint and map: <class 'tf2.LookupException'>: "sr1/map" passed to lookupTransform argument target_frame does not exist. 
[fleet_adapter.py-1] [INFO] [1738578226.278909825] [smartrover_command_handle]: Failed to update robot [sr1]: Unable to get transform between base_footprint and map
[fleet_adapter.py-1] [INFO] [1738578226.279203447] [smartrover_command_handle]: Failed to pose of robot [sr1]
[fleet_adapter.py-1] [INFO] [1738578226.380687105] [smartrover_command_handle]: Unable to get transform between base_footprint and map: <class 'tf2.LookupException'>: "sr1/map" passed to lookupTransform argument target_frame does not exist. 
[fleet_adapter.py-1] [INFO] [1738578226.382560009] [smartrover_command_handle]: Failed to update robot [sr1]: Unable to get transform between base_footprint and map
[fleet_adapter.py-1] [INFO] [1738578226.384089616] [smartrover_command_handle]: Failed to pose of robot [sr1]
[fleet_adapter.py-1] [INFO] [1738578226.479308846] [smartrover_fleet_adapter]: Adding robot [sr1] to fleet [smartrover].
[fleet_adapter.py-1] [ERROR] [1738578226.479489489] [smartrover_fleet_adapter]: Unable to compute a location on the navigation graph for robot [sr1] being added to fleet [smartrover] using map [L1] and position [108.609, 135.576, -2.951] specified in the initial_state argument. This can happen if the map in initial_state does not match any of the map names in the navigation graph supplied or if the position reported in the initial_state is far way from the navigation graph. This robot will not be added to the fleet.
[fleet_adapter.py-1] [INFO] [1738578226.580214758] [smartrover_fleet_adapter]: Adding robot [sr1] to fleet [smartrover].
[fleet_adapter.py-1] [ERROR] [1738578226.580440085] [smartrover_fleet_adapter]: Unable to compute a location on the navigation graph for robot [sr1] being added to fleet [smartrover] using map [L1] and position [108.581, 135.655, -2.951] specified in the initial_state argument. This can happen if the map in initial_state does not match any of the map names in the navigation graph supplied or if the position reported in the initial_state is far way from the navigation graph. This robot will not be added to the fleet.
[fleet_adapter.py-1] [INFO] [1738578226.681924471] [smartrover_fleet_adapter]: Adding robot [sr1] to fleet [smartrover].
[fleet_adapter.py-1] [ERROR] [1738578226.682152234] [smartrover_fleet_adapter]: Unable to compute a location on the navigation graph for robot [sr1] being added to fleet [smartrover] using map [L1] and position [108.540, 135.694, -2.950] specified in the initial_state argument. This can happen if the map in initial_state does not match any of the map names in the navigation graph supplied or if the position reported in the initial_state is far way from the navigation graph. This robot will not be added to the fleet.
[fleet_adapter.py-1] [INFO] [1738578226.781983379] [smartrover_fleet_adapter]: Adding robot [sr1] to fleet [smartrover].
[fleet_adapter.py-1] [ERROR] [1738578226.782266358] [smartrover_fleet_adapter]: Unable to compute a location on the navigation graph for robot [sr1] being added to fleet [smartrover] using map [L1] and position [108.570, 135.764, -2.950] specified in the initial_state argument. This can happen if the map in initial_state does not match any of the map names in the navigation graph supplied or if the position reported in the initial_state is far way from the navigation graph. This robot will not be added to the fleet.
```

My fleet_adapter config file is as follows:
```
# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "smartrover"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # AIDLE
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  # actions: ["some_action_here"]
  finishing_request: "charge" # [park, charge, nothing]
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  robots:
    sr1:
      charger: "charger"
      responsive_wait: False # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting.
      # For Nav2RobotAdapter
      navigation_stack: 2
      initial_map: "L1"
      maps:
        L1:
          map_url: "/home/einfochips/my_map.yaml"
    
      initial_pose: [109.138, 135.746, -2.940]

  robot_state_update_frequency: 10.0 # Hz


# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems
reference_coordinates:
  L1:
    rmf: [[42.3770, 10.4130],
          [90.8730, 6.2020],
          [98.4800, 101.7010],
          [26.6190, 102.9240]
          ]
    robot: [[0.0848, 3.7000],
            [2.5200, 3.8600],
            [2.9100, -0.9010],
            [-0.7320, -0.9540]
            ]
```
Please guide me what else needs to be taken care of. Thank you.
